Lib/beranda/urls.py
from django.urls import path, re_path
from .views import beranda, message_post, message_table

app_name = 'beranda'

urlpatterns = [
    path('', beranda, name='beranda'),
    path('message_post', message_post, name='message_post'),
    path('result_table', message_table, name='result_table')
]

Scripts/beranda/urls.py
from django.urls import path, re_path
from .views import beranda, message_post, message_table

app_name = 'beranda'

urlpatterns = [
    path('', beranda, name='beranda'),
    path('message_post', message_post, name='message_post'),
    path('result_table', message_table, name='result_table')
]

beling/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

from beranda.views import beranda
from portofolio.views import portofolio
from kemampuan.views import kemampuan
from kotakpesan.views import kotakpesan

urlpatterns = [
    path('', include('beranda.urls', namespace='beranda')),
    path('portofolio/', portofolio),
    path('kemampuan/', kemampuan),
    path('kotakpesan/', kotakpesan),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

beranda/urls.py
from django.urls import path, re_path
from .views import beranda, message_post, message_table

app_name = 'beranda'

urlpatterns = [
    path('', beranda, name='beranda'),
    path('message_post', message_post, name='message_post'),
    path('result_table', message_table, name='result_table')
]

Lib/beranda/models.py
from django.db import models

# Create your models here.

Scripts/beranda/models.py
from django.db import models

# Create your models here.

beranda/models.py
from django.db import models

# Create your models here.

Lib/beranda/views.py
from django.shortcuts import render
from bukutamu.forms import Message_Form
from bukutamu.models import Message
from django.http import HttpResponseRedirect

# Create your views here.
def beranda(request):
    response = {}
    response = {
        'judul' : 'Beranda'
    }
    response['message_form'] = Message_Form
    return render(request, 'beranda.html', response)

def message_post(request):
    response = {}
    form = Message_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name'] if request.POST['name'] != "" else "Anonymous"
        response['email'] = request.POST['email'] if request.POST['email'] != "" else "Anonymous"
        response['message'] = request.POST['message']
        message = Message(
            name=response['name'], 
            email=response['email'], 
            message = response['message'])
        message.save()
        html ='form_result.html'
        return render(request, html, response)
    else:
        return HttpResponseRedirect('/')

def message_table(request):
    message = Message.objects.all()
    response = {
        'judul': 'Buku Tamu'
    }
    response['message'] = message
    html = 'table.html'
    return render(request, html , response)

Scripts/beranda/views.py
from django.shortcuts import render
from bukutamu.forms import Message_Form
from bukutamu.models import Message
from django.http import HttpResponseRedirect

# Create your views here.
def beranda(request):
    response = {}
    response = {
        'judul' : 'Beranda'
    }
    response['message_form'] = Message_Form
    return render(request, 'beranda.html', response)

def message_post(request):
    response = {}
    form = Message_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name'] if request.POST['name'] != "" else "Anonymous"
        response['email'] = request.POST['email'] if request.POST['email'] != "" else "Anonymous"
        response['message'] = request.POST['message']
        message = Message(
            name=response['name'], 
            email=response['email'], 
            message = response['message'])
        message.save()
        html ='form_result.html'
        return render(request, html, response)
    else:
        return HttpResponseRedirect('/')

def message_table(request):
    message = Message.objects.all()
    response = {
        'judul': 'Buku Tamu'
    }
    response['message'] = message
    html = 'table.html'
    return render(request, html , response)

beranda/views.py
from django.shortcuts import render
from bukutamu.forms import Message_Form
from bukutamu.models import Message
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required


# Create your views here.
def beranda(request):
    response = {}
    response = {
        'judul' : 'Beranda'
    }
    response['message_form'] = Message_Form
    return render(request, 'beranda.html', response)

def message_post(request):
    response = {}
    form = Message_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name'] if request.POST['name'] != "" else "Anonymous"
        response['email'] = request.POST['email'] if request.POST['email'] != "" else "Anonymous"
        response['message'] = request.POST['message']
        message = Message(
            name=response['name'], 
            email=response['email'], 
            message = response['message'])
        message.save()
        html ='form_result.html'
        return render(request, html, response)
    else:
        return HttpResponseRedirect('/')

@login_required
def message_table(request):
    message = Message.objects.all()
    response = {
        'judul': 'Buku Tamu'
    }
    response['message'] = message
    html = 'table.html'
    return render(request, html , response)

Scripts/beranda/templates/beranda.html
{% extends './layout/base.html' %}
{% load static %}
{% block body %}

<div class="container customPadding content tengahkan">
    <div class="card customPadding">
        <img src="{% static 'foto.png' %}" class="card-img-top fotoProfil rounded mx-auto d-block" alt="...">
        <div class="card-body">
            <p class="card-text text-justify">
                Nama saya Moh. Rizky, usia saya 22 tahun nama panggilan sehari-hari saya Kobe, saya mahasiswa Teknik
                Informatika Universitas Tadulako, Kota Palu, Sulawesi Tengah
                <br>
                Keinginan Saya
                Ada banyak, saya ingin mempelajari banyak hal baru, mempunyai banyak teman, dan hal-hal lain yang saya
                harapkan dapat membantu perkenmbangan saya ke depannya, terutama masuk surga
            </p>
            <a class="card-link" href="https://www.linkedin.com/in/morizkay/">LinkedIn</a>
            <a class="card-link float-right" href="https://wa.me/6281241996168">Hubungi Saya</a>
        </div>
    </div>
    <hr>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalFormPesan">
        Ingin menyampaikan sesuatu? Sampaikan di sini
    </button>

    <div class="modal fade" id="modalFormPesan" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Pesan</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <section name="form">
                        <form id="form" method="POST" action="{% url 'beranda:message_post' %}">
                            {% csrf_token %}
                            {{ message_form }}
                            <br>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </section>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock body %}